import { LanguageEnum } from "../enums/language.enum";

export class PushTokenDto {

    /**
     * Device push token generated by FCM.
     */
    public token: string;

    /**
     * Language of the device.
     */
    public language: LanguageEnum;
    
}
